name: Composer Normalize

on:
  push:

jobs:
  composer-normalize:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.0.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer-normalize
      - run: composer-normalize
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Composer Normalize
